/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stack health
         * @description Always returns HTTP 200 when the process can answer. Degraded
         *     dependencies are reported in the body via `status`, not via the
         *     status code. The `migrations` object is omitted when the pending
         *     check could not run (for example when Postgres is unreachable).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a clip
         * @description Claim a slug with a text body. Returns 201 when the name is free or
         *     expired. Live collisions return 409 with `slug_in_use`.
         */
        post: operations["createClip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a live clip
         * @description Returns the stored body for a live clip. Missing and expired slugs both
         *     return 404 with the same error shape.
         */
        get: operations["getClip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check whether a slug looks claimable
         * @description Advisory read-only check: reports whether a name currently appears free.
         *     Does not reserve the name. Invalid or reserved slugs return the same
         *     validation error shape as create.
         */
        get: operations["getClipAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Overall status derived from the checks that completed
             * @enum {string}
             */
            status: "ok" | "degraded";
            database: components["schemas"]["DatabaseHealth"];
            /** @description Present only when the pending-migration check completed */
            migrations?: components["schemas"]["MigrationHealth"];
            /**
             * Format: date-time
             * @description Postgres `now()` as RFC3339Nano UTC, when reachable
             */
            serverTime?: string;
        };
        DatabaseHealth: {
            reachable: boolean;
            /**
             * Format: int64
             * @description Round-trip latency in milliseconds when reachable
             */
            latencyMs?: number;
        };
        MigrationHealth: {
            pending: boolean;
            /** Format: int64 */
            currentVersion: number;
        };
        ErrorResponse: {
            /** @description Machine-readable error code */
            code: string;
            /** @description Human-readable message */
            message: string;
        };
        CreateClipRequest: {
            /** @description Case-sensitive clip name */
            slug: string;
            /** @description UTF-8 text body (256 KiB max) */
            body: string;
            /**
             * Format: int64
             * @description Chosen lifetime in seconds from the anonymous preset set (10 minutes,
             *     1 hour, or 2 hours). Omitted values use the default preset (2 hours).
             * @enum {integer}
             */
            ttlSeconds?: 600 | 3600 | 7200;
        };
        CreateClipResponse: {
            slug: string;
            /**
             * Format: date-time
             * @description Expiry anchored to creation time as RFC3339Nano UTC
             */
            expiresAt: string;
        };
        ReadClipResponse: {
            slug: string;
            body: string;
            /** Format: date-time */
            expiresAt: string;
            /**
             * Format: date-time
             * @description Server clock at response time as RFC3339Nano UTC
             */
            serverTime: string;
        };
        ClipAvailabilityResponse: {
            slug: string;
            /** @description True when the slug passes validation and has no live clip */
            available: boolean;
        };
    };
    responses: {
        /** @description Unknown path */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "not_found",
                 *       "message": "resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Path exists but does not answer this method */
        MethodNotAllowed: {
            headers: {
                /** @description Comma-separated methods this path accepts */
                Allow?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "method_not_allowed",
                 *       "message": "method not allowed"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request failed validation */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health payload observed for this request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    createClip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClipRequest"];
            };
        };
        responses: {
            /** @description Clip created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "slug": "my-note",
                     *       "expiresAt": "2026-07-27T09:00:00.000000000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateClipResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            /** @description Slug is held by a live clip */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "slug_in_use",
                     *       "message": "that name is in use right now"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getClip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exact slug string (case-sensitive) */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live clip */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "slug": "my-note",
                     *       "body": "hello\nworld\n",
                     *       "expiresAt": "2026-07-27T09:00:00.000000000Z",
                     *       "serverTime": "2026-07-27T07:00:00.000000000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ReadClipResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getClipAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exact slug string (case-sensitive) */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipAvailabilityResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
}
