// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clips.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimClip = `-- name: ClaimClip :one
INSERT INTO clips (slug, body, created_at, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
SET body = EXCLUDED.body,
    created_at = EXCLUDED.created_at,
    expires_at = EXCLUDED.expires_at
WHERE clips.expires_at <= now()
RETURNING slug, body, created_at, expires_at
`

type ClaimClipParams struct {
	Slug      string
	Body      string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ClaimClip(ctx context.Context, arg ClaimClipParams) (Clip, error) {
	row := q.db.QueryRow(ctx, claimClip,
		arg.Slug,
		arg.Body,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Clip
	err := row.Scan(
		&i.Slug,
		&i.Body,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLiveClip = `-- name: GetLiveClip :one
SELECT slug, body, created_at, expires_at
FROM clips
WHERE slug = $1
  AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetLiveClip(ctx context.Context, slug string) (Clip, error) {
	row := q.db.QueryRow(ctx, getLiveClip, slug)
	var i Clip
	err := row.Scan(
		&i.Slug,
		&i.Body,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
