// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const serverTime = `-- name: ServerTime :one
SELECT NOW()::timestamptz AS server_time
`

func (q *Queries) ServerTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, serverTime)
	var server_time pgtype.Timestamptz
	err := row.Scan(&server_time)
	return server_time, err
}
