// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Clip struct {
	Slug      string
	Body      string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
