// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimClip(ctx context.Context, arg ClaimClipParams) (Clip, error)
	GetLiveClip(ctx context.Context, slug string) (Clip, error)
	ServerTime(ctx context.Context) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
